name: PROD01-Back-Autodeploy-on app

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: methyx
          server: methyx.ddns.net
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.METH_SSH }}

          local_path: ./* # default is ./*
          remote_path: /home/methyx/homes/back/

          # sftp args
          args: "-o ConnectTimeout=5"

      - name: Connect with ssh
        uses: appleboy/ssh-action@master
        with:
          username: methyx
          host: methyx.ddns.net
          port: 22 # default is 22
          key: ${{ secrets.METH_SSH }}
          script: |
            cd /home/methyx/homes/back
            npm install
            pm2 delete index.js
            pm2 start index.js
